name: Update Models Catalog

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"  # Weekly (Sundays 00:00 UTC)

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Fetch models catalog
        run: |
          curl -sL https://models.github.ai/catalog/models > /tmp/raw.json || exit 1
          echo '--- Begin raw models response (truncated to 2000 chars) ---'
          node - <<'LOG'
          const fs = require('fs');
          try {
            let txt = fs.readFileSync('/tmp/raw.json','utf8');
            if (txt.length > 2000) txt = txt.slice(0,2000) + '\n...[truncated]';
            console.log(txt);
          } catch (e) {
            console.log('Could not read raw.json', e.message);
          }
          LOG
          echo '--- End raw models response ---'
          node - <<'EOF'
          const fs = require('fs');
          try {
            const raw = JSON.parse(fs.readFileSync('/tmp/raw.json','utf8'));
            const list = Array.isArray(raw) ? raw
              : (raw && Array.isArray(raw.models) ? raw.models : []);
            const simplified = list.map(m => ({
              id: m.id || m.slug || m.name,
              label: m.displayName || m.name || m.id || m.slug || 'Model'
            })).filter(x => x.id);
            const payload = { updated: new Date().toISOString(), models: simplified };
            fs.writeFileSync('public/models-catalog.json', JSON.stringify(payload, null, 2) + '\n');
          } catch (e) {
            console.error('Failed to process models catalog', e);
            process.exit(1);
          }
          EOF
      - name: Commit if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/models-catalog.json || true
          # Always create a commit (even if no file changes) for auditing purposes.
          git commit --allow-empty -m "chore: update models catalog $(date -u +%Y-%m-%dT%H:%M:%SZ)" || true
          git push
